### ISSUE TITLE
Decryption does not work

### ISSUE THREAD

**Issue by svidem** [emrekizildas/EntityFrameworkCore.EncryptColumn#1]
I have tested you example https://github.com/emrekizildas/EntityFrameworkCore.EncryptColumn.Example and the first time it works, the second time I run it I get the following output:

```
﻿﻿ID: 9c2016b2-bf54-47d0-a9d0-23d94858ecad
Firstname: Emre
Lastname: Kizildas
Email Address: 
Identity Number: 
ID: d2a1252a-c7b3-41c6-b87a-e88ede34144a
Firstname: Emre
Lastname: Kizildas
Email Address: kizildas@icloud.com
Identity Number: 12345678901
```

It seems like it can't decrypt objects created by another instance of the DBContext.

**Comment by svidem** [comment]
Found the problem, add buffer when initializing the memory stream on row 52 in GenerateEncryptionProvider.

From
`using MemoryStream memoryStream = new();`
To 
`using MemoryStream memoryStream = new(buffer);`

**Comment by emrekizildas** [comment]
#

**Comment by emrekizildas** [comment]
It's closed.
#2
