### ISSUE TITLE
5.0.6 data loss bug

### ISSUE THREAD

**Issue by gala-s** [emrekizildas/EntityFrameworkCore.EncryptColumn#12]
The current release writes an empty string to the database instead of the encrypted value. I was able to verify this using the example project, after upgrading that project to EncryptColumn 5.0.6.

Looking at the repository history, it looks like the issue may have been resolved [here](https://github.com/emrekizildas/EntityFrameworkCore.EncryptColumn/commit/a7247663a669eb53a6f2b22786564139dd79d957) back in August, but an updated NuGet package wasn't published afterward.

**Comment by gala-s** [comment]
I did some testing with previous versions and 3.1 is also affected, it looks like the initial release is the only one that writes the encrypted value to the DB.

**Comment by jsucupira** [comment]
For me the only package that worked was v1. the other two (3 and 5) were saying blank data.

**Comment by marcwlux** [comment]
You need to compile the project from source. It works fine. The nuget-package doesn't work.
