### ISSUE TITLE
Feature Request: Consider Using DataProtection APIs for encryption key management

### ISSUE THREAD

**Issue by wrobbins** [emrekizildas/EntityFrameworkCore.EncryptColumn#5]
Microsoft has built in support for encryption key secret storage using the [DataProtection APIs](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/introduction?view=aspnetcore-5.0). 

Using these interfaces you could generate and store the encryption key(s) used in [`GenerateEncryptionProvider.cs`](https://github.com/emrekizildas/EntityFrameworkCore.EncryptColumn/blob/a724766/EntityFramework.Core.EncryptDBColumn/Util/GenerateEncryptionProvider.cs#L11) in a configurable, secure way.

**Comment by emrekizildas** [comment]
Hi @wrobbins , I have tried this before, but since DataProtection library constantly generates a new key based on the data, it is very difficult to decipher the encrypted data with which key it was encrypted with.
